# this is a pull request pipeline running on pr to main in opened and synchronize events and calls reusable security-scans.yml and after that reusable build-test.yml 
name: PR Pipeline
on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize]
    paths-ignore:
      - 'README.md'
      - '.github/workflows/**'
jobs:
  security-scans:
    uses: ./.github/workflows/reusable-security-scan.yml
    secrets: inherit
    
  build-test-frontend:
    needs: security-scans
    uses: ./.github/workflows/reusable-build-test.yml
    with:
      working_directory: ./netflix-clone/frontend
      run_build: true

  build-test-backend:
    needs: security-scans
    uses: ./.github/workflows/reusable-build-test.yml
    with:
      working_directory: ./netflix-clone/backend
      run_build: false

