name: Security Scans

on:
  workflow_call:

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      
      - name: Install ESLint
        run: npm install -g eslint
      
      - name: Run ESLint on frontend
        run: eslint ./netflix-clone/frontend/src --max-warnings 0
        continue-on-error: false
      
      - name: Run ESLint on backend
        run: eslint ./netflix-clone/backend --max-warnings 0
        continue-on-error: false

  sonarqube:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        with:
          args: >
           -Dsonar.projectKey=netflix-devsecops
           -Dsonar.organization=dikshitbonu-bit

  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Run GitLeaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  npm-audit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        directory: [./netflix-clone/frontend, ./netflix-clone/backend]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      
      - name: Run npm audit
        working-directory: ${{ matrix.directory }}
        run: npm audit --audit-level=high

  hadolint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Run Hadolint on frontend Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: ./netflix-clone/frontend/Dockerfile
          failure-threshold: warning
      
      - name: Run Hadolint on backend Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: ./netflix-clone/backend/Dockerfile
          failure-threshold: warning